server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/users
    username: myuser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
